### ISSUE TITLE
as a particle CLI developer I'd like to be able to use this module and publish it

### ISSUE THREAD

**Issue by m-mcgowan** [spark/binary-version-reader#7]
Can we make this repo public so it's usable by particle CLI? 

It would be instrumental in allowing particle CLI to automatically detect the type of binary and flash it to the appropriate DFU address, so the user doesn't have to specify flags for that.

https://github.com/spark/particle-cli/issues/32#issuecomment-134748800

**Comment by m-mcgowan** [comment]
Great Scott! Just saw this was released!

**Comment by dmiddlecamp** [comment]
:)
